# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: RicardoCabral.icuvisor
PackageVersion: 1.7.2
InstallerLocale: und
InstallerType: wix
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-09-30
InstallationMetadata:
  DefaultInstallLocation: "%LocalAppData%\\Programs\\icuvisor"
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ricardocabral/icuvisor/releases/download/v1.7.2/icuvisor_1.7.2_windows_amd64.msi
  InstallerSha256: C900672AF15DC9A37BB021512B597E269C19F0ADA0249E9CFC6279811EEDFEC5
  ProductCode: "{D658284C-D030-4033-BE07-4D4755AF624C}"
  AppsAndFeaturesEntries:
  - ProductCode: "{D658284C-D030-4033-BE07-4D4755AF624C}"
    UpgradeCode: "{8F557483-04AB-41DF-B138-3F979AF6496F}"
- Architecture: arm64
  InstallerUrl: https://github.com/ricardocabral/icuvisor/releases/download/v1.7.2/icuvisor_1.7.2_windows_arm64.msi
  InstallerSha256: 8CC46D9F7AD33A0395FD5C59E212C1E2F12CDE228C2EFBE8AB426BEAAA1BD9A0
  ProductCode: "{799D1848-8F19-408C-B63B-24277C299FBE}"
  AppsAndFeaturesEntries:
  - ProductCode: "{799D1848-8F19-408C-B63B-24277C299FBE}"
    UpgradeCode: "{8F557483-04AB-41DF-B138-3F979AF6496F}"
ManifestType: installer
ManifestVersion: 1.12.0
