# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Docker.docker-credential-wincred
PackageVersion: 0.9.10
PackageLocale: en-US
Publisher: docker
PublisherUrl: https://github.com/docker
PublisherSupportUrl: https://github.com/docker/docker-credential-helpers/issues
PackageName: docker-credential-wincred
PackageUrl: https://github.com/docker/docker-credential-helpers
License: MIT
LicenseUrl: https://github.com/docker/docker-credential-helpers/blob/HEAD/LICENSE
ShortDescription: Provides a helper to use Windows credentials manager as store.
Moniker: docker-credential-wincred
Tags:
- docker
ReleaseNotes: |-
  ## What's Changed

  • update to go1.26.9
  • build(deps)：bump actions/upload-artifact from 7.0.1 to 7.0.2
  • build(deps)：bump codecov/codecov-action from 7.0.0 to 7.1.1
  • build(deps)：bump docker/setup-qemu-action from 4.2.0 to 4.3.0
  • build(deps)：bump softprops/action-gh-release from 3.0.2 to 3.0.3
  • build(deps)：bump the docker-actions group


  **Full Changelog**：https://github.com/docker/docker-credential-helpers/compare/v0.9.9...v0.9.10
ReleaseNotesUrl: https://github.com/docker/docker-credential-helpers/releases/tag/v0.9.10
ManifestType: defaultLocale
ManifestVersion: 1.12.0
