# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Docker.docker-credential-wincred
PackageVersion: 0.9.10
InstallerType: portable
Commands:
- docker-credential-wincred
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/docker/docker-credential-helpers/releases/download/v0.9.10/docker-credential-wincred-v0.9.10.windows-amd64.exe
  InstallerSha256: 04833862D29A06A6F9353EF0619B7385F37EE3CE1650DE5AD3EBE9C3F2EBE233
- Architecture: arm64
  InstallerUrl: https://github.com/docker/docker-credential-helpers/releases/download/v0.9.10/docker-credential-wincred-v0.9.10.windows-arm64.exe
  InstallerSha256: 8E7D988B0CACA4E0BBF75E2F683DCA02067C93D3C0BF2F1E421FFC6748E6B3D9
ManifestType: installer
ManifestVersion: 1.12.0
