# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Miller.Miller
PackageVersion: 6.22.0
InstallerType: zip
NestedInstallerType: portable
UpgradeBehavior: install
ReleaseDate: 2026-09-25
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: miller-6.22.0-windows-386/mlr.exe
  InstallerUrl: https://github.com/johnkerl/miller/releases/download/v6.22.0/miller-6.22.0-windows-386.zip
  InstallerSha256: A397AD3FE4AC7B7730ABCCF55562692419CB067F222C4D1F85768EC1B548D631
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: miller-6.22.0-windows-amd64/mlr.exe
  InstallerUrl: https://github.com/johnkerl/miller/releases/download/v6.22.0/miller-6.22.0-windows-amd64.zip
  InstallerSha256: A8B7F5FE321528D181C771948F631115B9C17A8EBDF1C5809DE835349A9DD304
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: miller-6.22.0-windows-arm64/mlr.exe
  InstallerUrl: https://github.com/johnkerl/miller/releases/download/v6.22.0/miller-6.22.0-windows-arm64.zip
  InstallerSha256: 451949350EFD6EF1357EFC2E2D5A265F1FF3FC47AA27878707560C6EE8A001C1
ManifestType: installer
ManifestVersion: 1.12.0
