# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: D2L.BMX
PackageVersion: 3.4.0
PackageLocale: en-US
Publisher: D2L
PublisherUrl: https://github.com/Brightspace
PublisherSupportUrl: https://github.com/Brightspace/bmx/issues
PackageName: BMX
PackageUrl: https://github.com/Brightspace/bmx
License: Apache-2.0
LicenseUrl: https://github.com/Brightspace/bmx/blob/HEAD/LICENSE
ShortDescription: BMX provides API access to your AWS accounts using existing Okta credentials.
Tags:
- aws
- iam
- okta
- vulcan
ReleaseNotes: |-
  ## What's Changed
  • Switch to use D2L npm proxy registry by @cfbao in https://github.com/Brightspace/bmx/pull/530
  • CI：Use teams instead of team in vulcan-approval by @boarnoah in https://github.com/Brightspace/bmx/pull/531
  • use identity engine cookie for passwordless by @gord5500 in https://github.com/Brightspace/bmx/pull/532


  **Full Changelog**：https://github.com/Brightspace/bmx/compare/v3.3.0...v3.4.0
ReleaseNotesUrl: https://github.com/Brightspace/bmx/releases/tag/v3.4.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
