# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: caomengxuan666.WinuxCmd
PackageVersion: 1.1.6
InstallerType: zip
NestedInstallerType: portable
Commands:
- winuxcmd
ReleaseDate: 2026-10-10
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: WinuxCmd-1.1.6-win-x64/usr/bin/winuxcmd.exe
  InstallerUrl: https://github.com/unixwin/WinuxCmd/releases/download/v1.1.6/WinuxCmd-1.1.6-win-x64.zip
  InstallerSha256: EB3EC8D0AEF12938998121AE30EA084FB414348E9EA2B5808C7C1AF9762E332C
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: WinuxCmd-1.1.6-win-arm64/usr/bin/winuxcmd.exe
  InstallerUrl: https://github.com/unixwin/WinuxCmd/releases/download/v1.1.6/WinuxCmd-1.1.6-win-arm64.zip
  InstallerSha256: AA5DFEF0DC00E617334C345236E0BC99B519284B15A3750E884E95AE04F421CC
ManifestType: installer
ManifestVersion: 1.12.0
