# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: mq1.TinyWiiBackupManager
PackageVersion: 6.1.4
InstallerLocale: en-US
InstallerType: portable
UpgradeBehavior: uninstallPrevious
ProductCode: TinyWiiBackupManager
ReleaseDate: 2026-10-09
AppsAndFeaturesEntries:
- ProductCode: TinyWiiBackupManager
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/mq1/TinyWiiBackupManager/releases/download/v6.1.4/TinyWiiBackupManager-v6.1.4-windows-x86.exe
  InstallerSha256: D05BC54BED5B1509AC7CD57F87E2F78B062F961F216B6A612169941AF7B196C6
- Architecture: x64
  InstallerUrl: https://github.com/mq1/TinyWiiBackupManager/releases/download/v6.1.4/TinyWiiBackupManager-v6.1.4-windows-x64.exe
  InstallerSha256: 64C4D5EE08695F131D49F956E02727581C835E3EFFB159A37EDA7107F776C5A3
- Architecture: arm64
  InstallerUrl: https://github.com/mq1/TinyWiiBackupManager/releases/download/v6.1.4/TinyWiiBackupManager-v6.1.4-windows-arm64.exe
  InstallerSha256: 8C2803D8B1FC468C17AECE0D966A86A81F94088BD5C059A6F0BF10E7F4609DB4
ManifestType: installer
ManifestVersion: 1.12.0
