# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Loupedeck.Loupedeck
PackageVersion: 6.4.1.364
InstallerLocale: en-US
InstallerType: exe
Scope: machine
InstallerSwitches:
  SilentWithProgress: /quiet
ReleaseDate: 2026-09-16
Installers:
- Architecture: x86
  InstallerUrl: https://loupedeck-support.devops.logitech.io/hubfs/Knowledge%20Base/LD%20Software%20Downloads/6.4.1/LoupedeckInstaller_6.4.1.364.exe
  InstallerSha256: 884167502EA854E14DE35B39BAC7C91C203EB502F08A8667A202297E501C4A15
ManifestType: installer
ManifestVersion: 1.12.0
