# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Loupedeck.Loupedeck
PackageVersion: 6.4.1.364
PackageLocale: en-US
Publisher: LoupeDeck Oy
PackageName: Loupedeck
PackageUrl: https://loupedeck.com/downloads
License: Unknown
Copyright: Copyright (c) LoupeDeck Ltd. All rights reserved.
ShortDescription: Loupedeck console control software
ManifestType: defaultLocale
ManifestVersion: 1.12.0
