# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: SanthoshReddy352.NammaAgent
PackageVersion: 2.3.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --cli
  SilentWithProgress: --cli
UpgradeBehavior: install
ReleaseDate: 2026-08-05
AppsAndFeaturesEntries:
- DisplayName: Namma Agent
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SanthoshReddy352/Namma-Agent/releases/download/v2.3.2/NammaAgentInstaller-2.3.2.exe
  InstallerSha256: 38C3BA3855821505842E7E2C7C809C9BB3BA88391251690CA3FF9A4F3AFAF5AD
ManifestType: installer
ManifestVersion: 1.12.0
