# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: AdGuard.dnsproxy
PackageVersion: 0.86.0
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: windows-386/dnsproxy.exe
  InstallerUrl: https://github.com/AdguardTeam/dnsproxy/releases/download/v0.86.0/dnsproxy-windows-386-v0.86.0.zip
  InstallerSha256: 703F6009BF3BE73A3CD13067FB1B253A423980AD0B2B01F17A3177D2A884205B
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: windows-amd64/dnsproxy.exe
  InstallerUrl: https://github.com/AdguardTeam/dnsproxy/releases/download/v0.86.0/dnsproxy-windows-amd64-v0.86.0.zip
  InstallerSha256: DEDC186DDD4B96BF92474F91D972F67DA0824E0141D09E3102FD96DB9F8A0DBC
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: windows-arm64/dnsproxy.exe
  InstallerUrl: https://github.com/AdguardTeam/dnsproxy/releases/download/v0.86.0/dnsproxy-windows-arm64-v0.86.0.zip
  InstallerSha256: 5E65305B3A45919FB766F547CC1EC728DF818702A01C8AFD6F1E9192AFC84CB6
ManifestType: installer
ManifestVersion: 1.12.0
