# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: AdGuard.dnsproxy
PackageVersion: 0.86.0
PackageLocale: en-US
Publisher: AdGuard
PublisherUrl: https://adguard.com/
PublisherSupportUrl: https://github.com/AdguardTeam/dnsproxy/issues
PackageName: DNS Proxy
PackageUrl: https://github.com/AdguardTeam/dnsproxy
License: Apache-2.0
LicenseUrl: https://github.com/AdguardTeam/dnsproxy/blob/HEAD/LICENSE
ShortDescription: Simple DNS proxy with DoH, DoT, DoQ and DNSCrypt support
Tags:
- dns
- dns-over-https
- dns-over-quic
- dns-over-tls
- dnscrypt
- golang
- open-source
- proxy
ReleaseNotes: |-
  ### Added

  • `config.dist.yaml` is now packed into release packages (#513).

  ### Changed

  • Interface method [`upstream.Upstream.Exchange`] now accepts a context.
  • Function [`upstream.ExchangeParallel`] now accepts a context.
  • Function [`upstream.ExchangeAll`] now accepts a context.

  [`upstream.Upstream.Exchange`]：https://pkg.go.dev/github.com/AdguardTeam/dnsproxy@v0.86.0/upstream#Upstream.Exchange
  [`upstream.ExchangeParallel`]：     https://pkg.go.dev/github.com/AdguardTeam/dnsproxy@v0.86.0/upstream#ExchangeParallel
  [`upstream.ExchangeAll`]：             https://pkg.go.dev/github.com/AdguardTeam/dnsproxy@v0.86.0/upstream#ExchangeAll

  ### Removed

  • Package [`fastip`] is no longer exported.

  [`fastip`]：https://pkg.go.dev/github.com/AdguardTeam/dnsproxy@v0.85.0/fastip
ReleaseNotesUrl: https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.86.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
