# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Microsoft.Wassette
PackageVersion: 0.8.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: wassette.exe
  PortableCommandAlias: wassette
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/wassette/releases/download/v0.8.0/wassette_0.8.0_windows_amd64.zip
  InstallerSha256: 4032409E00D46B9A6BB765FCBE61474A14C979C4FB10C63211A9427FAF0CBB38
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/microsoft/wassette/releases/download/v0.8.0/wassette_0.8.0_windows_arm64.zip
  InstallerSha256: 52B7E21F4DC25D468F8DAF80677D40AD89034BBEA9F2A8A6E2CB182237458BD8
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
